spring:
  application:
    name: servicio-oauth
  config:
    import: "optional:configserver:http://config-server:8888/"
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
