spring:
  application:
    name: servicio-oauth
  config:
    import: "optional:configserver:http://localhost:8888/"
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
