spring:
    application:
        name: servicio-items
#    config:
#        import: "optional:configserver:"
server:
    port: 8002
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
