spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: file:/home/danny/config-server
                    #uri: https://github.com/Danny626/servicio-items-config
                    #username: 
                    #password:
server:
    port: 8888
